[meta]
name = "arch-minimal"
description = "ThinkPad x220"

[packages]
list = [
    "firefox",
    "niri",
    "fuzzel",
    "htop",
    "alacritty",
    "cpupower",
    "ffmpeg",
    "xwayland-satellite",
    "xdg-desktop-portal-wlr",
    "qt6-multimedia-ffmpeg",
    "xdg-desktop-portal-gtk",
    "ttf-jetbrains-mono-nerd",
    "bluez",
    "bluez-utils",
    "wireplumber",
    "pipewire",
    "pipewire-pulse",
    "pipewire-alsa",
    "noto-fonts-cjk",
    "unzip",
    "fastfetch",
    "brightnessctl",
    "tlp",
    "tlp-pd",
    "tlp-rdw",
    "powertop",
]

[configs]
targets = [
    ".config/niri",
    ".config/alacritty",
    ".config/fuzzel",
    ".config/helix",
    ".config/fastfetch",
    ".config/xdg-desktop-portal/portals.conf",
    ".bashrc"
]
