# --- Настройки окна ---
font="JetBrainsMono Nerd Font:size=11"
# Делаем его заметнее, как ты хотел
width=40
tabs=4
horizontal-pad=20
vertical-pad=15
inner-pad=10

# Центрирование
anchor=center
lines=10

[colors]
# Используем значения из btop 
# Фон: main_bg (#1d1f21) с прозрачностью (например, dd)
background=1d1f21dd
# Основной текст: main_fg (#c5c8c6)
text=c5c8c6ff
# Совпадение иконок/ключей: hi_fg (#81beb7)
match=81beb7ff
# Фон выделенной строки: selected_bg (#282a2e)
selection=282a2eff
# Текст выделенной строки (акцентный зеленый): temp_start (#b5bd68)
selection-text=b5bd68ff
# Рамка: cpu_box (#81a2be)
border=81a2beff

[border]
width=2
radius=10
