# ~/.config/fuzzel/fuzzel.ini

font=JetBrainsMono Nerd Font:size=14
width=40
tabs=4
horizontal-pad=20
vertical-pad=15
inner-pad=10
anchor=center
lines=10

[colors]
# Глубокий темный фон с прозрачностью dd (как в твоем btop)[cite: 1]
background=1d1f21dd
# Обычный текст в списке — спокойный белый (не серый, но и не слишком яркий)
text=e0e0e0ff
# Цвет букв, которые совпали при поиске — оставляем чистый белый
match=ffffffff
# Фон выделенной строки — чуть светлее общего фона[cite: 1]
selection=282a2eff
# Текст выделенной строки — теперь чисто белый и яркий[cite: 1]
selection-text=e0e0e0ff
# Строгая тонкая рамка вокруг меню[cite: 1]
border=333333ff

[border]
width=2
radius=10
