# Наследуемся от стандартной прозрачной темы
inherits = "base16_transparent"

# Переопределяем только то, что нам нужно
"ui.linenr" = { fg = "gray" }          # Обычные номера строк теперь отчетливо серые
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] } # Текущая строка — яркая
